// 🔧 Generated by zest v0.2.0 (Type-Aware)
import { renderHook } from '@testing-library/react';
import { create } from 'zustand';

const useTestStore = create((set) => ({
  count: 0,
  isDark: false,
  increment: jest.fn(),
  toggleTheme: jest.fn(),
}));

describe('useTestStore', () => {
  it('initializes with correct types', () => {
    const { result } = renderHook(() => useTestStore());
    expect(result.current).toBeDefined();
  });
});
