import { StoreProperty } from '../parser/storeParser';

export function generateTestFile(properties: StoreProperty[]): string {
    const stateLines = properties.filter(p => !p.isAction).map(p => `  ${p.key}: ${p.mockValue},`).join('\n');
    const actionLines = properties.filter(p => p.isAction).map(p => `  ${p.key}: jest.fn(),`).join('\n');

    return `// 🔧 Generated by zest v0.2.0 (Type-Aware)
import { renderHook } from '@testing-library/react';
import { create } from 'zustand';

const useTestStore = create((set) => ({
${stateLines}
${actionLines}
}));

describe('useTestStore', () => {
  it('initializes with correct types', () => {
    const { result } = renderHook(() => useTestStore());
    expect(result.current).toBeDefined();
  });
});
`;
}