import { StoreSchema } from '../parser/storeParser';

export function generateTestFile(store: StoreSchema): string {
  const stateInit = store.stateKeys.map(k => `  ${k}: null,`).join('\n');
  const actionMocks = store.actionKeys.map(k => `  ${k}: jest.fn(),`).join('\n');

  return `// 🔧 Generated by zest v0.1.0
import { renderHook, act } from '@testing-library/react';
import { create } from 'zustand';

const useTestStore = create((set) => ({
${stateInit}
${actionMocks}
}));

describe('${store.name}', () => {
  it('initializes correctly', () => {
    const { result } = renderHook(() => useTestStore());
    expect(result.current).toBeDefined();
  });
});
`;
}